// data.jsx — flotta di veicoli + dati helper Ottibull

const FLEET = [
  {
    id: 'mansardato-mclouis-373',
    cat: 'camper',
    type: 'Capuchina',
    name: 'McLouis Tandy 373',
    seats: 6, sleeps: 6, length: 6.99, year: 2024,
    transmission: 'Manual', license: 'B',
    pricePerDay: 169, deposit: 1200,
    location: 'Verona', tone: '',
    rating: 4.9, reviews: 87,
    pet: true, premium: true,
    features: ['Aire acondicionado', 'Cocina 3 fuegos', 'Baño con ducha', 'Calefacción', 'Toldo', 'Portabicicletas', 'TV 24"', 'Paneles solares'],
    summary: 'Capuchina spazioso e luminoso. Letti separati per i bambini, basculante adulti. La scelta più richiesta dalle famiglie.',
  },
  {
    id: 'semintegrale-burstner-680',
    cat: 'camper',
    type: 'Perfilada',
    name: 'Bürstner Lyseo 680',
    seats: 4, sleeps: 4, length: 6.99, year: 2025,
    transmission: 'Automático', license: 'B',
    pricePerDay: 189, deposit: 1500,
    location: 'Milano', tone: 'cielo',
    rating: 4.8, reviews: 54,
    pet: false, premium: true,
    features: ['Aire acondicionado', 'Cama abatible eléctrica', 'Baño separado', 'Cambio automático', 'Cruise control', 'Inverter 1500W'],
    summary: 'Compatto da guidare, premium dentro. Cama abatible eléctrica e bagno separato dalla doccia.',
  },
  {
    id: 'van-possl-summit',
    cat: 'camper',
    type: 'Van compacta',
    name: 'Pössl Summit 540',
    seats: 4, sleeps: 2, length: 5.41, year: 2024,
    transmission: 'Manual', license: 'B',
    pricePerDay: 119, deposit: 1000,
    location: 'Bologna', tone: 'bosco',
    rating: 4.9, reviews: 142,
    pet: true, premium: false,
    features: ['Techo elevable', 'Cocina 2 fuegos', 'Ducha exterior', 'Frigo 90L', 'Panel solar 100 W'],
    summary: 'Por debajo de 5,5 m. Pasa por todo, aparca en cualquier sitio. Ideal para dos, en pareja o con perro.',
  },
  {
    id: 'roulotte-fendt-bianco',
    cat: 'roulotte',
    type: 'Caravana',
    name: 'Fendt Bianco Activ 515',
    seats: 4, sleeps: 4, length: 7.30, year: 2024,
    transmission: '—', license: 'B (con E para >750 kg)',
    pricePerDay: 89, deposit: 800,
    location: 'Verona', tone: '',
    rating: 4.7, reviews: 38,
    pet: true, premium: false,
    features: ['Camas gemelas', 'Sofá convertible', 'Cocina 3 fuegos', 'Calefacción Truma', 'Toldo', 'Portabombonas'],
    summary: 'Se engancha y tira. Una verdadera casa al llegar, cómoda para quedarse varios días en el mismo sitio.',
  },
  {
    id: 'roulotte-knaus-sudwind',
    cat: 'roulotte',
    type: 'Caravana compatta',
    name: 'Knaus Südwind 450',
    seats: 4, sleeps: 4, length: 6.40, year: 2023,
    transmission: '—', license: 'B',
    pricePerDay: 69, deposit: 700,
    location: 'Torino', tone: 'cielo',
    rating: 4.6, reviews: 22,
    pet: false, premium: false,
    features: ['Litera', 'Remolcable con carné B', 'Frigo 142L', 'Calefacción'],
    summary: 'Por debajo de 1.500 kg, remolcable con carné B. Para quien empieza con la caravana sin complicaciones.',
  },
  {
    id: 'moto-bmw-gs1250',
    cat: 'moto',
    type: 'Adventure touring',
    name: 'BMW R 1250 GS',
    seats: 2, sleeps: null, length: null, year: 2024,
    transmission: 'Manual', license: 'A',
    pricePerDay: 159, deposit: 2000,
    location: 'Milano', tone: 'terra',
    rating: 4.9, reviews: 64,
    pet: false, premium: true,
    features: ['Maletas laterales', 'Top case', 'Calefacción manopole', 'Cruise control', 'ABS Pro', 'Ride modes'],
    summary: 'L\'adventure di riferimento. Lunghi viaggi, sterrato leggero, due personas con bagagli senza problemi.',
  },
  {
    id: 'moto-honda-africatwin',
    cat: 'moto',
    type: 'Adventure touring',
    name: 'Honda Africa Twin 1100',
    seats: 2, sleeps: null, length: null, year: 2025,
    transmission: 'DCT (automática)', license: 'A',
    pricePerDay: 149, deposit: 1800,
    location: 'Bologna', tone: 'terra',
    rating: 4.8, reviews: 41,
    pet: false, premium: true,
    features: ['Cambio DCT', 'Maletas de aluminio', 'Faro LED', 'Cruise control', 'Suspensiones electrónicas'],
    summary: 'Cambio automático DCT, perfetta in città e fuori. La più semplice da guidare nel segmento adventure.',
  },
  {
    id: 'moto-yamaha-tracer',
    cat: 'moto',
    type: 'Sport touring',
    name: 'Yamaha Tracer 9 GT',
    seats: 2, sleeps: null, length: null, year: 2024,
    transmission: 'Manual', license: 'A',
    pricePerDay: 119, deposit: 1500,
    location: 'Verona', tone: 'terra',
    rating: 4.7, reviews: 29,
    pet: false, premium: false,
    features: ['Maletas laterales', 'Cruise control', 'Quickshifter', 'Faros cornering'],
    summary: 'Más asfalto que pista. Tres cilindros elásticos, posición cómoda para los largos recorridos.',
  },
];

const CITIES = [
  'Verona', 'Milano', 'Bologna', 'Torino', 'Roma', 'Firenze',
  'Padova', 'Venezia', 'Bergamo', 'Brescia', 'Trento', 'Bolzano',
  'Genova', 'Modena',
];

const DESTINATIONS = [
  { id: 'dolomiti', name: 'Dolomiti', sub: 'Carreteras panorámicas y lagos alpinos', tone: 'bosco' },
  { id: 'toscana', name: 'Toscana', sub: 'Colinas, pueblos, aguas termales', tone: '' },
  { id: 'sardegna', name: 'Sardegna', sub: 'Costa salvaje y calas escondidas', tone: 'cielo' },
  { id: 'capo-nord', name: 'Cabo Norte', sub: 'El viaje de los viajes, tres semanas', tone: 'terra' },
];

const STORIES = [
  { id: 's1', title: 'Da Verona a Cabo Norte, 21 giorni', meta: 'Historia de viaje · 8 min', tone: 'cielo' },
  { id: 's2', title: 'Dolomitas en caravana: la guía honesta', meta: 'Guía · 6 min', tone: 'bosco' },
  { id: 's3', title: 'Costa Esmeralda en moto, fuera de temporada', meta: 'Historia de viaje · 5 min', tone: 'terra' },
];

window.OTTI_DATA = { FLEET, CITIES, DESTINATIONS, STORIES };
